language: node_js
dist: bionic
node_js:
  - '12'
  - '13'
  - '14'

install: yarn --frozen-lockfile
script:
  - node --version
  - yarn --version
  - yarn lint
  - yarn build
  - yarn test

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
